Repository prebid/prebid-mobile-ios, pull requests merged in 2019-08, with the labels that each got.

#231 Support for stored auction and bid response ids
  src/PrebidMobile/PrebidMobile/Prebid.swift
  src/PrebidMobile/PrebidMobile/RequestBuilder.swift
  src/PrebidMobile/PrebidMobileTests/FetchingLogictests/RequestBuilderTests.swift
  src/PrebidMobile/PrebidMobileTests/PrebidTests.swift
Labels: feature

#227 Prebid timeout editable
  src/PrebidMobile/PrebidMobile/AdUnits/AdUnit.swift
  src/PrebidMobile/PrebidMobile/BidManager.swift
  src/PrebidMobile/PrebidMobile/Prebid.swift
  src/PrebidMobile/PrebidMobile/RequestBuilder.swift
  src/PrebidMobile/PrebidMobileTests/FetchingLogictests/BidManagerTests.swift
Labels: enhancement

#233 `bidderNames` were exposed for Objective-C code
  src/PrebidMobile/PrebidMobile/Constants.swift
  src/PrebidMobile/PrebidMobile/Prebid.swift
  src/PrebidMobile/PrebidMobileTests/FetchingLogictests/RequestBuilderTests.swift
Labels: bug

#230 Refactoring/Improvement
  example/Swift/PrebidDemo/PrebidDemo.xcodeproj/project.pbxproj
  example/Swift/PrebidDemo/PrebidDemoTests/PBViewTool.swift
  example/Swift/PrebidDemo/PrebidDemoTests/PrebidDemoTests.swift
  src/PrebidMobile/PrebidMobile.xcodeproj/project.pbxproj
  src/PrebidMobile/PrebidMobile/AdUnits/AdUnit.swift
  src/PrebidMobile/PrebidMobile/CollectionExtension.swift
  src/PrebidMobile/PrebidMobile/RequestBuilder.swift
  src/PrebidMobile/PrebidMobileTests/AdUnitTests/AdUnitTests.swift
  src/PrebidMobile/PrebidMobileTests/AdUnitTests/BannerAdUnitTests.swift
  src/PrebidMobile/PrebidMobileTests/AdUnitTests/InterstItialAdUnitTests.swift
  src/PrebidMobile/PrebidMobileTests/FetchingLogictests/RequestBuilderTests.swift
  src/PrebidMobile/PrebidMobileTests/UnitTests/CollectionExtensionTest.swift
Labels: enhancement
