Repository prebid/prebid-mobile-ios, pull requests merged in 2021-04, with the labels that each got.

#370 Location Manager to use Last known location
  Podfile.lock
  PrebidMobile.xcodeproj/project.pbxproj
  Source/Location.swift
  Source/Prebid.swift
  Source/RequestBuilder.swift
  Tests/FetchingLogictests/RequestBuilderTests.swift
Labels: enhancement

#371 Bitcode issue
  .travis.yml
  PrebidMobile.xcodeproj/project.pbxproj
  scripts/buildPrebidMobile.sh
Labels: bug, enhancement, needs docs

#381 [Not master] Disallow cookies in HTTP when deviceAccessConsent=false
  Source/RequestBuilder.swift
  Tests/FetchingLogictests/RequestBuilderTests.swift
Labels: not master

#378 Disallow cookies in HTTP when deviceAccessConsent=false
  Source/RequestBuilder.swift
  Tests/FetchingLogictests/RequestBuilderTests.swift
Labels: enhancement
